(function() {var implementors = {};
implementors["gstreamer_video"] = ["impl <a class=\"trait\" href=\"gstreamer_video/trait.IsA.html\" title=\"trait gstreamer_video::IsA\">IsA</a>&lt;<a class=\"struct\" href=\"gstreamer_base/auto/base_transform/struct.BaseTransform.html\" title=\"struct gstreamer_base::auto::base_transform::BaseTransform\">BaseTransform</a>&gt; for <a class=\"struct\" href=\"gstreamer_video/struct.VideoFilter.html\" title=\"struct gstreamer_video::VideoFilter\">VideoFilter</a>","impl <a class=\"trait\" href=\"gstreamer_video/trait.IsA.html\" title=\"trait gstreamer_video::IsA\">IsA</a>&lt;<a class=\"struct\" href=\"gstreamer/auto/element/struct.Element.html\" title=\"struct gstreamer::auto::element::Element\">Element</a>&gt; for <a class=\"struct\" href=\"gstreamer_video/struct.VideoFilter.html\" title=\"struct gstreamer_video::VideoFilter\">VideoFilter</a>","impl <a class=\"trait\" href=\"gstreamer_video/trait.IsA.html\" title=\"trait gstreamer_video::IsA\">IsA</a>&lt;<a class=\"struct\" href=\"gstreamer/auto/object/struct.Object.html\" title=\"struct gstreamer::auto::object::Object\">Object</a>&gt; for <a class=\"struct\" href=\"gstreamer_video/struct.VideoFilter.html\" title=\"struct gstreamer_video::VideoFilter\">VideoFilter</a>","impl <a class=\"trait\" href=\"gstreamer_video/trait.IsA.html\" title=\"trait gstreamer_video::IsA\">IsA</a>&lt;<a class=\"struct\" href=\"glib/object/struct.Object.html\" title=\"struct glib::object::Object\">Object</a>&gt; for <a class=\"struct\" href=\"gstreamer_video/struct.VideoFilter.html\" title=\"struct gstreamer_video::VideoFilter\">VideoFilter</a>","impl <a class=\"trait\" href=\"gstreamer_video/trait.IsA.html\" title=\"trait gstreamer_video::IsA\">IsA</a>&lt;<a class=\"struct\" href=\"glib/object/struct.Object.html\" title=\"struct glib::object::Object\">Object</a>&gt; for <a class=\"struct\" href=\"gstreamer_video/struct.VideoOverlay.html\" title=\"struct gstreamer_video::VideoOverlay\">VideoOverlay</a>",];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
