(function() {var implementors = {};
implementors["gstreamer"] = ["impl&lt;T:&nbsp;<a class=\"trait\" href=\"gstreamer/miniobject/trait.MiniObject.html\" title=\"trait gstreamer::miniobject::MiniObject\">MiniObject</a>&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/convert/trait.AsRef.html\" title=\"trait core::convert::AsRef\">AsRef</a>&lt;T&gt; for <a class=\"struct\" href=\"gstreamer/miniobject/struct.GstRc.html\" title=\"struct gstreamer::miniobject::GstRc\">GstRc</a>&lt;T&gt;","impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/convert/trait.AsRef.html\" title=\"trait core::convert::AsRef\">AsRef</a>&lt;<a class=\"struct\" href=\"gstreamer/structure/struct.StructureRef.html\" title=\"struct gstreamer::structure::StructureRef\">StructureRef</a>&gt; for <a class=\"struct\" href=\"gstreamer/structure/struct.Structure.html\" title=\"struct gstreamer::structure::Structure\">Structure</a>","impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/convert/trait.AsRef.html\" title=\"trait core::convert::AsRef\">AsRef</a>&lt;<a class=\"enum\" href=\"https://doc.rust-lang.org/nightly/core/option/enum.Option.html\" title=\"enum core::option::Option\">Option</a>&lt;<a class=\"primitive\" href=\"https://doc.rust-lang.org/nightly/std/primitive.u64.html\">u64</a>&gt;&gt; for <a class=\"struct\" href=\"gstreamer/struct.ClockTime.html\" title=\"struct gstreamer::ClockTime\">ClockTime</a>","impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/convert/trait.AsRef.html\" title=\"trait core::convert::AsRef\">AsRef</a>&lt;<a class=\"type\" href=\"num_rational/type.Rational32.html\" title=\"type num_rational::Rational32\">Rational32</a>&gt; for <a class=\"struct\" href=\"gstreamer/struct.Fraction.html\" title=\"struct gstreamer::Fraction\">Fraction</a>",];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
