(function() {var implementors = {};
implementors["glib"] = ["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/std/error/trait.Error.html\" title=\"trait std::error::Error\">Error</a> for <a class=\"struct\" href=\"glib/error/struct.Error.html\" title=\"struct glib::error::Error\">Error</a>","impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/std/error/trait.Error.html\" title=\"trait std::error::Error\">Error</a> for <a class=\"struct\" href=\"glib/error/struct.BoolError.html\" title=\"struct glib::error::BoolError\">BoolError</a>",];
implementors["gst_plugin"] = ["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/std/error/trait.Error.html\" title=\"trait std::error::Error\">Error</a> for <a class=\"enum\" href=\"gst_plugin/adapter/enum.AdapterError.html\" title=\"enum gst_plugin::adapter::AdapterError\">AdapterError</a>",];
implementors["gstreamer"] = ["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/std/error/trait.Error.html\" title=\"trait std::error::Error\">Error</a> for <a class=\"struct\" href=\"gstreamer/struct.ErrorMessage.html\" title=\"struct gstreamer::ErrorMessage\">ErrorMessage</a>","impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/std/error/trait.Error.html\" title=\"trait std::error::Error\">Error</a> for <a class=\"enum\" href=\"gstreamer/enum.IteratorError.html\" title=\"enum gstreamer::IteratorError\">IteratorError</a>","impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/std/error/trait.Error.html\" title=\"trait std::error::Error\">Error</a> for <a class=\"struct\" href=\"gstreamer/struct.StateChangeError.html\" title=\"struct gstreamer::StateChangeError\">StateChangeError</a>","impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/std/error/trait.Error.html\" title=\"trait std::error::Error\">Error</a> for <a class=\"enum\" href=\"gstreamer/enum.FlowError.html\" title=\"enum gstreamer::FlowError\">FlowError</a>","impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/std/error/trait.Error.html\" title=\"trait std::error::Error\">Error</a> for <a class=\"enum\" href=\"gstreamer/enum.PadLinkError.html\" title=\"enum gstreamer::PadLinkError\">PadLinkError</a>","impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/std/error/trait.Error.html\" title=\"trait std::error::Error\">Error</a> for <a class=\"enum\" href=\"gstreamer/enum.ClockError.html\" title=\"enum gstreamer::ClockError\">ClockError</a>",];
implementors["num_rational"] = ["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/std/error/trait.Error.html\" title=\"trait std::error::Error\">Error</a> for <a class=\"struct\" href=\"num_rational/struct.ParseRatioError.html\" title=\"struct num_rational::ParseRatioError\">ParseRatioError</a>",];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
