(function() {var implementors = {};
implementors["glib"] = [{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/std/error/trait.Error.html\" title=\"trait std::error::Error\">Error</a> for <a class=\"struct\" href=\"glib/error/struct.Error.html\" title=\"struct glib::error::Error\">Error</a>",synthetic:false,types:["glib::error::Error"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/std/error/trait.Error.html\" title=\"trait std::error::Error\">Error</a> for <a class=\"struct\" href=\"glib/error/struct.BoolError.html\" title=\"struct glib::error::BoolError\">BoolError</a>",synthetic:false,types:["glib::error::BoolError"]},];
implementors["gst_plugin"] = [{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/std/error/trait.Error.html\" title=\"trait std::error::Error\">Error</a> for <a class=\"enum\" href=\"gst_plugin/error/enum.FlowError.html\" title=\"enum gst_plugin::error::FlowError\">FlowError</a>",synthetic:false,types:["gst_plugin::error::FlowError"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/std/error/trait.Error.html\" title=\"trait std::error::Error\">Error</a> for <a class=\"enum\" href=\"gst_plugin/adapter/enum.AdapterError.html\" title=\"enum gst_plugin::adapter::AdapterError\">AdapterError</a>",synthetic:false,types:["gst_plugin::adapter::AdapterError"]},];
implementors["gstreamer"] = [{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/std/error/trait.Error.html\" title=\"trait std::error::Error\">Error</a> for <a class=\"struct\" href=\"gstreamer/struct.ErrorMessage.html\" title=\"struct gstreamer::ErrorMessage\">ErrorMessage</a>",synthetic:false,types:["gstreamer::error::ErrorMessage"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/std/error/trait.Error.html\" title=\"trait std::error::Error\">Error</a> for <a class=\"struct\" href=\"gstreamer/struct.StateChangeError.html\" title=\"struct gstreamer::StateChangeError\">StateChangeError</a>",synthetic:false,types:["gstreamer::enums::StateChangeError"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/std/error/trait.Error.html\" title=\"trait std::error::Error\">Error</a> for <a class=\"enum\" href=\"gstreamer/enum.FlowError.html\" title=\"enum gstreamer::FlowError\">FlowError</a>",synthetic:false,types:["gstreamer::enums::FlowError"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/std/error/trait.Error.html\" title=\"trait std::error::Error\">Error</a> for <a class=\"enum\" href=\"gstreamer/enum.PadLinkError.html\" title=\"enum gstreamer::PadLinkError\">PadLinkError</a>",synthetic:false,types:["gstreamer::enums::PadLinkError"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/std/error/trait.Error.html\" title=\"trait std::error::Error\">Error</a> for <a class=\"enum\" href=\"gstreamer/enum.ClockError.html\" title=\"enum gstreamer::ClockError\">ClockError</a>",synthetic:false,types:["gstreamer::enums::ClockError"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/std/error/trait.Error.html\" title=\"trait std::error::Error\">Error</a> for <a class=\"enum\" href=\"gstreamer/enum.TagError.html\" title=\"enum gstreamer::TagError\">TagError</a>",synthetic:false,types:["gstreamer::enums::TagError"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/std/error/trait.Error.html\" title=\"trait std::error::Error\">Error</a> for <a class=\"enum\" href=\"gstreamer/enum.IteratorError.html\" title=\"enum gstreamer::IteratorError\">IteratorError</a>",synthetic:false,types:["gstreamer::iterator::IteratorError"]},];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
