(function() {var implementors = {};
implementors["gstreamer_webrtc"] = [{text:"impl <a class=\"trait\" href=\"gstreamer_webrtc/prelude/trait.IsA.html\" title=\"trait gstreamer_webrtc::prelude::IsA\">IsA</a>&lt;<a class=\"struct\" href=\"glib/object/struct.Object.html\" title=\"struct glib::object::Object\">Object</a>&gt; for <a class=\"struct\" href=\"gstreamer_webrtc/struct.WebRTCDTLSTransport.html\" title=\"struct gstreamer_webrtc::WebRTCDTLSTransport\">WebRTCDTLSTransport</a>",synthetic:false,types:["gstreamer_webrtc::auto::web_rtcdtls_transport::WebRTCDTLSTransport"]},{text:"impl <a class=\"trait\" href=\"gstreamer_webrtc/prelude/trait.IsA.html\" title=\"trait gstreamer_webrtc::prelude::IsA\">IsA</a>&lt;<a class=\"struct\" href=\"glib/object/struct.Object.html\" title=\"struct glib::object::Object\">Object</a>&gt; for <a class=\"struct\" href=\"gstreamer_webrtc/struct.WebRTCICETransport.html\" title=\"struct gstreamer_webrtc::WebRTCICETransport\">WebRTCICETransport</a>",synthetic:false,types:["gstreamer_webrtc::auto::web_rtcice_transport::WebRTCICETransport"]},{text:"impl <a class=\"trait\" href=\"gstreamer_webrtc/prelude/trait.IsA.html\" title=\"trait gstreamer_webrtc::prelude::IsA\">IsA</a>&lt;<a class=\"struct\" href=\"glib/object/struct.Object.html\" title=\"struct glib::object::Object\">Object</a>&gt; for <a class=\"struct\" href=\"gstreamer_webrtc/struct.WebRTCRTPReceiver.html\" title=\"struct gstreamer_webrtc::WebRTCRTPReceiver\">WebRTCRTPReceiver</a>",synthetic:false,types:["gstreamer_webrtc::auto::web_rtcrtp_receiver::WebRTCRTPReceiver"]},{text:"impl <a class=\"trait\" href=\"gstreamer_webrtc/prelude/trait.IsA.html\" title=\"trait gstreamer_webrtc::prelude::IsA\">IsA</a>&lt;<a class=\"struct\" href=\"glib/object/struct.Object.html\" title=\"struct glib::object::Object\">Object</a>&gt; for <a class=\"struct\" href=\"gstreamer_webrtc/struct.WebRTCRTPSender.html\" title=\"struct gstreamer_webrtc::WebRTCRTPSender\">WebRTCRTPSender</a>",synthetic:false,types:["gstreamer_webrtc::auto::web_rtcrtp_sender::WebRTCRTPSender"]},{text:"impl <a class=\"trait\" href=\"gstreamer_webrtc/prelude/trait.IsA.html\" title=\"trait gstreamer_webrtc::prelude::IsA\">IsA</a>&lt;<a class=\"struct\" href=\"glib/object/struct.Object.html\" title=\"struct glib::object::Object\">Object</a>&gt; for <a class=\"struct\" href=\"gstreamer_webrtc/struct.WebRTCRTPTransceiver.html\" title=\"struct gstreamer_webrtc::WebRTCRTPTransceiver\">WebRTCRTPTransceiver</a>",synthetic:false,types:["gstreamer_webrtc::auto::web_rtcrtp_transceiver::WebRTCRTPTransceiver"]},];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
