(function() {var implementors = {};
implementors["glib"] = ["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/alloc/borrow/trait.ToOwned.html\" title=\"trait alloc::borrow::ToOwned\">ToOwned</a> for <a class=\"struct\" href=\"glib/struct.VariantTy.html\" title=\"struct glib::VariantTy\">VariantTy</a>",];
implementors["gstreamer"] = ["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/alloc/borrow/trait.ToOwned.html\" title=\"trait alloc::borrow::ToOwned\">ToOwned</a> for <a class=\"struct\" href=\"gstreamer/structure/struct.StructureRef.html\" title=\"struct gstreamer::structure::StructureRef\">StructureRef</a>","impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/alloc/borrow/trait.ToOwned.html\" title=\"trait alloc::borrow::ToOwned\">ToOwned</a> for <a class=\"struct\" href=\"gstreamer/caps/struct.CapsRef.html\" title=\"struct gstreamer::caps::CapsRef\">CapsRef</a>","impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/alloc/borrow/trait.ToOwned.html\" title=\"trait alloc::borrow::ToOwned\">ToOwned</a> for <a class=\"struct\" href=\"gstreamer/tags/struct.TagListRef.html\" title=\"struct gstreamer::tags::TagListRef\">TagListRef</a>","impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/alloc/borrow/trait.ToOwned.html\" title=\"trait alloc::borrow::ToOwned\">ToOwned</a> for <a class=\"struct\" href=\"gstreamer/buffer/struct.BufferRef.html\" title=\"struct gstreamer::buffer::BufferRef\">BufferRef</a>","impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/alloc/borrow/trait.ToOwned.html\" title=\"trait alloc::borrow::ToOwned\">ToOwned</a> for <a class=\"struct\" href=\"gstreamer/sample/struct.SampleRef.html\" title=\"struct gstreamer::sample::SampleRef\">SampleRef</a>","impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/alloc/borrow/trait.ToOwned.html\" title=\"trait alloc::borrow::ToOwned\">ToOwned</a> for <a class=\"struct\" href=\"gstreamer/bufferlist/struct.BufferListRef.html\" title=\"struct gstreamer::bufferlist::BufferListRef\">BufferListRef</a>","impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/alloc/borrow/trait.ToOwned.html\" title=\"trait alloc::borrow::ToOwned\">ToOwned</a> for <a class=\"struct\" href=\"gstreamer/context/struct.ContextRef.html\" title=\"struct gstreamer::context::ContextRef\">ContextRef</a>","impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/alloc/borrow/trait.ToOwned.html\" title=\"trait alloc::borrow::ToOwned\">ToOwned</a> for <a class=\"struct\" href=\"gstreamer/toc/struct.TocRef.html\" title=\"struct gstreamer::toc::TocRef\">TocRef</a>","impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/alloc/borrow/trait.ToOwned.html\" title=\"trait alloc::borrow::ToOwned\">ToOwned</a> for <a class=\"struct\" href=\"gstreamer/toc/struct.TocEntryRef.html\" title=\"struct gstreamer::toc::TocEntryRef\">TocEntryRef</a>",];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
